### ISSUE TITLE
Invalid memory reference with seasonal inside tryCatch

### ISSUE THREAD

**Issue by mtreadwell** [christophsax/seasonal#154]
I have several hundred thousand timeseries from a database table that need seasonal adjustment. In order to adjust these series I am using packages doParallel, foreach, seasonal.

Since some of the series will inevitably fail, I am following the advice in the README:

> It is useful to wrap the call to seas in a try statement; that way, an error will not break the execution. You need to develop an error handling strategy for these cases: You can either drop them, use them without adjustment or switch to a different automated routine.

Basically, I attempt to seasonally adjust the series using seasonal and if it fails I will adjust the series with simple additive decomposition. My function looks like the following:

        x13_adjust <- function(timeseries) {

          adjusted_series <- tryCatch({
            adj <- withTimeout(
              {seas(timeseries)},
              timeout = 30,
              onTimeout = 'error'
            )
            adj_status <- 'X13'
            list(adj, adj_status)
          },
          warning = function(w){
            adj <- timeseries - decompose(timeseries)$seasonal
            adj_status <- 'DECOMPOSE'
            w.adjustment <- list(adj, adj_status)
            return(w.adjustment)
          },
          error = function(e){
            adj <- timeseries - decompose(timeseries)$seasonal
            adj_status <- 'DECOMPOSE'
            e.adjustment <- list(adj, adj_status)
            return(e.adjustment)
          },
          TimeoutException = function(te){
            adj <- timeseries - decompose(timeseries)$seasonal
            adj_status <- 'DECOMPOSE'
            te.adjustment <- list(adj, adj_status)
            return(te.adjustment)
          })

          return(adjusted_series)

        }

Since the data is inside of a database table in tall (narrow) data format with many dimensions I use a foreach loop in parallel to access the data at the appropriate dimensional granularity. Then I convert the data to a timeseries, adjust the series, then re-add metadata and format the series for writing back to the database.

However, while the program is running I am repeatedly receiving this message:
`Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`

In order to test the source of this message I have done a couple of things, neither of which has addressed the issue:

1. Remove/add `.errorhandling = 'pass'` from the foreach call
2. Change `%dopar%` to `%do%` to process sequentially

The only thing I can do to stop the message is to remove `seas()` from `tryCatch()`

If I just use `seas()` and let the series with errors be removed from the output then I do not receive the message. Additionally, if I remove `seas()` and use another function inside of `tryCatch()` (even one that fails periodically) then I do not receive the message.

Is there a known issue with these two functions?

**Comment by christophsax** [comment]
Can you narrow the problem? Try to find out which series do fail, and run them without parallelization. If you figure out what series is crashing seasonal, I may help. Use `dput` to copy/paste the failing series. I don't think the parallel stuff is the problem here.

The dev version of seasonal contains `robust.seas`, like `seas` but should *always* work. [Here](https://github.com/christophsax/forecast-tests/blob/master/analysis/1-auto.arima-v-X13-v-ets.R) is an example with 3000 series.

**Comment by mtreadwell** [comment]
Here is an example of the error from `seas()` that is causing issues inside of `tryCatch()`
    Error: X-13 has returned a non-zero exist status, which means that the current spec file cannot be processed for an unknown reason.
    In addition: Warning message:
    running command 'C:\Windows\system32\cmd.exe /c "C:/R/3-2.2.2/library/x13binary/bin/x13ashtml.exe"
    C:\Temp\RtmpqAV5VR\x13a60309873fa/iofile -n -s' had status 3 

The following files contain three bad series obtained from `dput`

[bad-series.txt](https://github.com/christophsax/seasonal/files/143871/bad-series.txt)
[bad-series2.txt](https://github.com/christophsax/seasonal/files/143878/bad-series2.txt)
[bad-series3.txt](https://github.com/christophsax/seasonal/files/143879/bad-series3.txt)

**Comment by mtreadwell** [comment]
Looking at the files written by x13ashtml it seems like the series is adjusted. I see the iofile.html with all of the adjustment diagnostics.

However, the iofile_err.html file is filled with garbage.

**Comment by christophsax** [comment]
You are right, X-13 produces some stuff, but also returns an error code. So I think seasonal behaves as expected, by not proceeding and returning the error instead. SEATS generally does not like short series, and your examples are *very* short. If you use X11 instead, everything works fine.

Here are your examples:

```
s1 <- structure(c(0, 0, 0, 0, 5045000, 18820999, 29801610.75, 32893959, 
26412724, 39891068, 23509653, 31953360, 20762638, 18839531, 9997909, 
13843946, 20625616, 8964680, 10363470, 23314718), .Tsp = c(2005, 
2009.75, 4), class = "ts")

s2 <- structure(c(149666666.666667, -106729004, 6.8e+07, 85733002, 
86266998, -78401001, 80632004, 34111999, -13341003, -34615997, 
43692001, 59204003, -7399002, -46449002, 50379002, -17472001, 
19272000, -10437000), .Tsp = c(2007.5, 2011.75, 4), class = "ts")

s3 <- structure(c(5.65e+08, 224442017, 3.14e+08, -72460007, 220460007, 
157866028, 140608002, 78662002, 28134003, 61944992, 35578999, 
-5390000, 280400997, 213652985, 260255005, 222954010, 321515961, 
149963012), .Tsp = c(2007.5, 2011.75, 4), class = "ts")
```

This is not working (SEATS default):

    seas(s1)
    seas(s2)
    seas(s3)

But this is (X11):

    seas(s1, x11 = "")
    seas(s2, x11 = "")
    seas(s3, x11 = "")

With `robust.seas` from the latest dev, you should now also got the switch to X-11 automatically. `robust.seas` should be great to use in loops, lapply or for any form of parallel use:

    robust.seas(s1)
    robust.seas(s2)
    robust.seas(s3)

To install the latest dev, use:

    devtools::install_github("christophsax/seasonal")

**Comment by mtreadwell** [comment]
Ok

Installing the latest dev, `robust.seas()` seems to be mostly working. It does have a few problems with certain series and returns no data but I should be able to handle those with `tryCatch()`. Unfortunately there still seems to be some sort of problem using `robust.seas()` in `tryCatch()`.

For example, with this series
[tseries.txt](https://github.com/christophsax/seasonal/files/151730/tseries.txt)

`robust.seas(dget(tseries.txt))$series$s11` returns no results due to an error

So let's try using `tryCatch()`

    devtools::install_github('christophsax/seasonal')
    
    library(seasonal)
    
    adjust_series <- function(timeseries) {
      
      adjusted_series <- tryCatch({
        adj <- robust.seas(timeseries)$series$s11
        adj_status <- 'X13'
        list(adj, adj_status)
      },
      warning = function(w){
        adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
        adj_status <- 'DECOMPOSE'
        w.adjustment <- list(adj, adj_status)
        return(w.adjustment)
      },
      error = function(e){
        adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
        adj_status <- 'DECOMPOSE'
        e.adjustment <- list(adj, adj_status)
        return(e.adjustment)
      })
      
      return(adjusted_series)
      
    }

    tseries <- dget('tseries.txt')

    adjust_series(tseries)

The good news is that `robust.seas()` seems to be handling most series and returning appropriate errors when necessary. In this case the series gets returned as decomposed as expected. Great so far.

Now look at this series that works with robust.seas():
[good-tseries.txt](https://github.com/christophsax/seasonal/files/151748/good-tseries.txt)

    good.tseries <- dget('good-tseries.txt')
    
    # this returns an adjusted series
    robust.seas(good.tseries)
    
    # this returns a decomposed series
    # even though robust.seas() does not return an error
    adjust_series <- good.tseries

What could be going on that a function that returns no errors is getting caught by `tryCatch()`?

**Comment by christophsax** [comment]
Sorry for the late answer!

Your first series is failing because it is of frequency 2, which is only supported by SEATS. At the same time it is too short for SEATS, so `robust.seas` tries to use X11. Need to think about what to do with these kind of series.

Now, for your main problem, `tryCatch` was not working because `robust.seas` just returned the error message, but did not actually fail. I changed that in the lastest dev version of seasonal, so your function `adjust_series` should now work.

**Comment by mtreadwell** [comment]
Sorry for taking so long to test this. Unfortunately, I am still having the same issue even with the newest version of the package.

See the comments below:

    devtools::install_github('christophsax/seasonal')
    library(seasonal)
    
    adjust_series <- function(timeseries) {
      
      adjusted_series <- tryCatch({
        adj <- robust.seas(timeseries)$series$s11
        adj_status <- 'X13'
        list(adj, adj_status)
      },
      warning = function(w){
        adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
        adj_status <- 'DECOMPOSE'
        w.adjustment <- list(adj, adj_status)
        return(w.adjustment)
      },
      error = function(e){
        adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
        adj_status <- 'DECOMPOSE'
        e.adjustment <- list(adj, adj_status)
        return(e.adjustment)
      })
      
      return(adjusted_series)
      
    }
    
    tseries <- dget('c:/prometheus/tseries.txt')
    
    ## this is adjusting the series without error
    robust.seas(tseries)$series$s11
    
    ## this function still returns 'DECOMPOSE'
    adjust_series(tseries)

**Comment by mtreadwell** [comment]
Some extra information, I've created a test script to run a single bad series and before the segmentation fault I get an error that points to a specific problem.

![capture2](https://cloud.githubusercontent.com/assets/10984846/15788428/87b535d2-2995-11e6-9ffe-41398aef370d.PNG)

So the issue is somehow related to read_udg function.

https://github.com/christophsax/seasonal/blob/337d1d8688fed94dcb1fc680ecf64eba5c1623be/R/read_udg.R

Any information on a timeline for a fix?

**Comment by christophsax** [comment]
Sorry for the delay! The `robust.seasonal` function is a bit queued, so there has not been much progress. 

However, your issue is independent of that, but I am almost sure it is also independent of the udg function. It's only that the udg function try read a file that is not there after a failed X-13 run. (Admittedly, the error message could be better.)

The segmentation fault is a typical problem of the binary, most likely caused by some unpleasant input series. Can you isolate the time series that causes the crash and put it here? Please put it here as R code, so that I don't have to download the files. Thanks.

P.S., I somehow overlooked your next to last post, and tried to run it (using seas, rather than robust.seas). But this works fine here:
(if you copy your data in the code, replicating it requires only copy / paste)

```
library(seasonal)

tseries <- structure(c(0, 0, 0, 907976990, 128834000, 131257004, 130257996, 
131052002, 128201996, 742364634, 1085156738, 1081509766, 1925197876, 
2109801270, 2064310303, 1907775146, 3323271973, 132051269.5, 
130110397, 131556061, 132369431, 132092804, 129221222, 130657013, 
132347717, 0, 0, 0, 907976990, 128834000, 131257004, 130257996, 
131052002, 128201996, 742364634, 1085156738, 1081509766, 1925197876, 
2109801270, 2064310303, 1907775146, 3323271973, 132051269.5), .Tsp = c(2005, 
2015.5, 4), class = "ts")

adjust_series <- function(timeseries) {

  adjusted_series <- tryCatch({
    adj <- seas(timeseries)$series$s11
    adj_status <- 'X13'
    list(adj, adj_status)
  },
  warning = function(w){
    adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
    adj_status <- 'DECOMPOSE'
    w.adjustment <- list(adj, adj_status)
    return(w.adjustment)
  },
  error = function(e){
    adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
    adj_status <- 'DECOMPOSE'
    e.adjustment <- list(adj, adj_status)
    return(e.adjustment)
  })

  return(adjusted_series)

}

seas(tseries)$series$s11

#            Qtr1       Qtr2       Qtr3       Qtr4
# 2005   96588452          0   19268537  859805648
# 2006  292862331  131257004   82086654   82880660
# 2007  292230327  742364634 1036985396 1100778303
# 2008 1577626910 2109801270 2083578840 1927043683
# 2009 3419860425  132051270  149378934  150824598
# 2010  228957883  132092804  148489759  149925550
# 2011  228936169          0   19268537  -48171342
# 2012  560406024  128834000   83085662  149526533
# 2013  227640454  128201996  761633171 1104425275
# 2014 1178098218 1925197876 2129069807 2083578840
# 2015 2004363598 3323271973  151319806       

## this function still returns 'DECOMPOSE'
adjust_series(tseries)

# [[1]]
#            Qtr1       Qtr2       Qtr3       Qtr4
# 2005   96588452          0   19268537  859805648
# 2006  292862331  131257004   82086654   82880660
# 2007  292230327  742364634 1036985396 1100778303
# 2008 1577626910 2109801270 2083578840 1927043683
# 2009 3419860425  132051270  149378934  150824598
# 2010  228957883  132092804  148489759  149925550
# 2011  228936169          0   19268537  -48171342
# 2012  560406024  128834000   83085662  149526533
# 2013  227640454  128201996  761633171 1104425275
# 2014 1178098218 1925197876 2129069807 2083578840
# 2015 2004363598 3323271973  151319806           

# [[2]]
# [1] "X13"


```

**Comment by mtreadwell** [comment]
Here is a series that is still giving me a problem.

    devtools::install_github("christophsax/seasonal")
    
    library(seasonal)
    
    bad.series <- structure(c(3238330403.66667, 110672852, 2382774658, 2491468018, 
                              2771596679, 3991519043, 7192062988, 3773342285, 517156250, 953443360, 
                              189968674, 597738662, 886041199, 1654700195, 323907288, 928887146, 
                              -48182984, -126732422), .Tsp = c(2011.5, 2015.75, 4), class = "ts")
    
    seas(bad.series, regression.variables = c('td', 'seasonal'))
    
    #Error: X-13 has returned a non-zero exist status, which means that the current spec file cannot be processed for an unknown reason.
    #In addition: Warning message:
    #running command 'C:\Windows\system32\cmd.exe /c "C:/R/R-3.2.2/library/x13binary/bin/x13ashtml.exe" C:\Temp\Rtmpc5efWB\x1315d81d46109a/iofile -n -s' had status 3 
    
    seas(bad.series)
    
    #Error: X-13 has returned a non-zero exist status, which means that the current spec file cannot be processed for an unknown reason.
    #In addition: Warning message:
    #running command 'C:\Windows\system32\cmd.exe /c "C:/R/R-3.2.2/library/x13binary/bin/x13ashtml.exe" C:\Temp\Rtmpc5efWB\x1315d82e2943ba/iofile -n -s' had status 3 
    
    robust.seas(bad.series)
    
    #use X-11
    
    #Call:
    #robust.seas(x = bad.series)
    
    #Coefficients:
    #         Constant  AR-Nonseasonal-01  
    #        1.744e+09          5.387e-01  
    
    #Warning message:
    #running command 'C:\Windows\system32\cmd.exe /c "C:/R/R-3.2.2/library/x13binary/bin/x13ashtml.exe" C:\Temp\Rtmpc5efWB\x1315d838274beb/iofile -n -s' had status 3 
    
    seas(bad.series, x11 = '')
    
    #Call:
    #seas(x = bad.series, x11 = "")
    
    #Coefficients:
    #         Constant  AR-Nonseasonal-01  
    #        1.744e+09          5.387e-01  
    
It is good to see here that X11 does work for the series. The problem is that my tryCatch will still produce the segmentation fault errors when trying the X13 adjustment.

![capture2](https://cloud.githubusercontent.com/assets/10984846/15789634/46808cf0-299b-11e6-8708-1660c4d52565.PNG)

**Comment by christophsax** [comment]
I don't see what's not working here: When I use `adjust_series()` on `bad.series` it will resort to `decompose` as intended:

```
library(seasonal)
bad.series <- structure(c(3238330403.66667, 110672852, 2382774658, 2491468018, 
                          2771596679, 3991519043, 7192062988, 3773342285, 517156250, 953443360, 
                          189968674, 597738662, 886041199, 1654700195, 323907288, 928887146, 
                          -48182984, -126732422), .Tsp = c(2011.5, 2015.75, 4), class = "ts")

adjust_series <- function(timeseries) {

  adjusted_series <- tryCatch({
    adj <- seas(timeseries)$series$s11
    adj_status <- 'X13'
    list(adj, adj_status)
  },
  warning = function(w){
    adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
    adj_status <- 'DECOMPOSE'
    w.adjustment <- list(adj, adj_status)
    return(w.adjustment)
  },
  error = function(e){
    adj <- timeseries - decompose(timeseries, type = 'additive')$seasonal
    adj_status <- 'DECOMPOSE'
    e.adjustment <- list(adj, adj_status)
    return(e.adjustment)
  })

  return(adjusted_series)

}

adjust_series(bad.series)

# sh: line 1: 38210 Bus error: 10           /Library/Frameworks/R.framework/Versions/3.3/Resources/library/x13binary/bin/x13ashtml /var/folders/8n/6xn1tf891q59s7qhrfjsmgrr0000gn/T//Rtmp51POKz/x13951b7444991/iofile -n -s 2> /dev/null
# [[1]]
#            Qtr1       Qtr2       Qtr3       Qtr4
# 2011                       4077455211   -9385507
# 2012 1791142976 2364033252 3610721487 3871460684
# 2013 6600431306 3645907519 1356281058  833385001
# 2014 -401663008  470303896 1725166007 1534641836
# 2015 -267724394  801452380  790941824 -246790781

# [[2]]
# [1] "DECOMPOSE"

```

**Comment by christophsax** [comment]
Or, is your whole R session crashing when you run my code above?

**Comment by mtreadwell** [comment]
Right, the code that you posted does return the decomposed series.

However, Rscript still outputs the segmentation fault errors, which was the original reason that I opened this issue.

![capture](https://cloud.githubusercontent.com/assets/10984846/15977895/069cbb5c-2f29-11e6-9e95-a54a0e2b7b54.PNG)

**Comment by christophsax** [comment]
The segfault is a problem of the X-13 binaries. It looks fine to me how seasonal is handling it. I guess we can close this thread?
